### ISSUE TITLE
Mobile Desing Fix for Create Popup

### ISSUE THREAD

**Issue by TheShiveshNetwork** [TheShiveshNetwork/readmekraft#12]
In the phone view of the website, the Create Readme Popup flows out of width.
The issue is shown in the attached screenshot:
![image](https://github.com/user-attachments/assets/40ae4177-ea32-4448-82f8-4aeb6163ef67)
This needs to be fixed for all the Create Markdown pages.

**Comment by priyank-mishra-1** [comment]
Hey @TheShiveshNetwork , I was hoping to contribute to this project under Hacktoberfest. Can I take this issue?

**Comment by TheShiveshNetwork** [comment]
Sure, I'll assign this to you.
